// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbbbjntausxrxushrbgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiYmJqbnRhdXN4cnh1c2hyYmdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0ODA1NzcsImV4cCI6MjA1MzA1NjU3N30.uV23tgy2QVfdn2sS4DO1WeQfwNIvTE-zYyRyqtIsa2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);